apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: busybox
  namespace: test # This should be ignored
  labels:
    name: busybox
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: busybox
    spec:    
      containers:
        - name: busybox
          image: busybox
          