apiVersion: batch/v1
kind: Job
metadata:
  name: init
spec:
  template:
    metadata:
      name: init
    spec:
      restartPolicy: Never
      containers:
        - name: init
          image: {{.build_var_anduin_initimage}}