kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-standard"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi