apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: consul
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: consul
    spec:
      containers:
        - name: consul
          image: anduin/consul:{{.consul_tag}}
  revisionHistoryLimit: 10